---
title: "Large District Photo Viewer"
author: "Chris Day"
date: "2023-09-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(exiftoolr) # you must install Exiftool to use this pacakge
library(leaflet)
library(htmlwidgets)
library(magick)
```

```{r}
photo_folder_path <- "D:/GitHub/Large-District-Tours/photos"
data_list <- list()
```

```{r}
#function that converts HEIC type photos to JPG
convert_heic_to_jpg <- function(photo_folder_path) {
  heic_files <- list.files(photo_folder_path, pattern = "\\.heic$", full.names = TRUE, ignore.case = TRUE)
  
  counter <- 0
  for (heic_file in heic_files) {
    jpg_file <- file.path(photo_folder_path, sprintf("%02d.jpg", counter))
    img <- image_read(heic_file)
    image_write(img, jpg_file, format = "jpg")
    file.rename(heic_file, file.path(photo_folder_path, sprintf("%02d.heic", counter)))
    counter <- counter + 1
  }
}

#function that delete .heic photos
delete_heic_files <- function(folder_path) {
  files <- list.files(path = folder_path, full.names = TRUE)

  heic_files <- files[grep("\\.heic$", files, ignore.case = TRUE)]
  if (length(heic_files) > 0) {
    file.remove(heic_files)
    cat(paste(length(heic_files), "HEIC file(s) deleted.\n"))
  } else {
    cat("No HEIC files found in the specified folder.\n")
  }
}
```

```{r}
#convert_heic_to_jpg(photo_folder_path)
#delete_heic_files(photo_folder_path)
```

```{r}
# Function to extract latitude and longitude from a photo
get_lat_lon <- function(file_path) {
  metadata <- exif_read(file_path)
  lat <- metadata$GPSLatitude
  lon <- metadata$GPSLongitude
    return(c(lat, lon))
}
text <- exif_read(paste0(photo_folder_path,'/00.heic'))
```


```{r}
# Read HEIC photos, extract coordinates, and store in data_list
counter <- 0
for (file_name in list.files(photo_folder_path, pattern = "\\.heic$", full.names = TRUE)) {
  coords <- get_lat_lon(file_name)
  jpg_file <- file.path(photo_folder_path, sprintf("%02d.jpg", counter))
  counter <- counter + 1
  if (!is.null(coords)) {
    data_list[[length(data_list) + 1]] <- list(
      lat = coords[1],
      lon = coords[2],
      photo_path = jpg_file
    )
  }
  if (is.null(coords)) {cat("No coords\n")}
}
```

```{r}
library(leaflet)
pts <- tibble(x = runif(10, 175, 176), 
              y = runif(10, -38, -37)) %>% 
  st_as_sf(coords = c("x", "y"), crs = 4326)

img <- glue::glue("https://github.com/IQAndreas/sample-images/blob/gh-pages/100-100-color/{11:20}.jpg?raw=true")

pts$img <- img

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = pts, group = "pts") %>%
  leafpop::addPopupImages(pts$img, group = "pts")
```




```{r}
#htmlwidgets::saveWidget(map, "map.html", selfcontained = TRUE)
```

```{r}
#library(sf)
#library(dplyr)
#library(mapview)
#
#pnt <- data.frame(x = 174.764474, y = -36.877245) %>% 
#  st_as_sf(coords = c("x", "y"), crs = 4326)
#
#img = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Mount_Eden.jpg/640px-Mount_Eden.jpg"
#download.file(img,destfile=paste0(getwd(), "/mounteden.jpg"))
#img_local = paste0(getwd(), "/IMG_2145.png")
#
#m = mapview(pnt, popup = FALSE)@map %>%
#  leafpop::addPopupImages("https://drive.google.com/file/d/1TupZX3kB5xEz9cOMLHOSjXQEthWFQFGQ/view?usp=sharing", group = "pnt")
#m
#mapshot(m, url = paste0(getwd(), "/testmap.html"))
```

```{r}
library(leaflet)
pts <- tibble(x = runif(10, 175, 176), 
              y = runif(10, -38, -37)) %>% 
  st_as_sf(coords = c("x", "y"), crs = 4326)

img <- glue::glue("https://github.com/IQAndreas/sample-images/blob/gh-pages/100-100-color/{11:20}.jpg?raw=true")

pts$img <- img

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = pts, group = "pts") %>%
  leafpop::addPopupImages(pts$img, group = "pts")
```


```{r}
data_name <- readOGR("data/map_file.kml")

data_name2 <- data.frame(data_name)

pts <- st_as_sf(data.frame(data_name2),
                coords = c("coords.x1", "coords.x2"), crs = 4326)

img <- c("images/picture_name.jpg") ##did this for every image I wanted to use, in the order 
##that matched up with the data points I wanted them associated with.

pts$img <- img

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = pts, group = "pts") %>%
  addPopupImages(pts$img, group = "pts", width = 300)
```

